server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location /api/ {
        proxy_pass http://localhost:8080/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # 24 hours should be enough right?
        # This very much feels like the sort of config that turns up in a Kevin Feige video.
        # Here's hoping!
        # Well actually, TODO: add regular ws ping to the backend
        proxy_read_timeout 24h;
    }
}
