spring.http.converters.preferred-json-mapper=jackson3
springdoc.default-produces-media-type=application/json

spring.datasource.url=jdbc:sqlite:///database.sqlite
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true